from collections import Counter

ciphertext = """PX LWZ XSXLQ DMES HDS WZUNMYR CB HYP JYILE FEBXD WOVPP KAFV RLCIY EC PVV POCID TAICIEDS ATDSOH RYG METCSOH FQ DSP MPWJUJ DHCIY EC PVV OZHVQ WCNRJ RULEE XWJSID DUH NCOBHJXHU SQ EVA AFFQAETY VWZCD DUH YTBA BZYH YMYRG SSIP JPJEPR PC KSH YENP CB AVY ZOS LMCRS RWO LPDP RAGZCH WSHPF BCI HLALTY HDSJP UPRRD KWG SZXUH ESS OHIPQNXS LBZ HYP ZPPW EC CCMPUU SGPF AOTS UHGP MIP HYPB DICP OHZ FQ WOIX OSYSZGHK JZC OJCKSHY VTYU SOJ XDKI TY HDS CLQK SQ XCNRFC LU XSP TEFVD RM QZFBP RFZP ALP OONY CZUK WLFFKB WZUNIO TB OSTCHA E XLGPSI CLUK EZ QKBKCRS EWW CPVVCV HRO TBPC KSLZ VTYU DS GZXYIO LZH VZD FYYPWHU VZD PHPTNS WBU SLZ ATWZ PC UZPPRLES WZC WLMI ZYS NWER WV VFWS PVVX DSP ZYS XM FYH ALP QFAS GPRWPPD CB AZOGSI PLFPV WPOS XZ EVA DFHHY SQ EVA FZYJ IYE EVAFV HHYI DZAA KYZ ULWTDHAR R WDZX LWZEOENH VJ XPB WBU POCID XONQYPG HKLTBOH KSH HVXTSO CW XRYHZC OJR FY WOI GPFU GCZSLW ZQ AKIEE GVSX EVAM WZXNLE QCN HYP IYIPOCI CW XLKHWPSWFKS YPGEZFU KRD QLEC MIP HYP SVAPC CB HYP UPRR NCQZU YRA FP FBZCEP LA ALD WJ HYTV TSXPBP KYPQ HPW SCLS YLG MEOPR PVRE LZMWOIN GFY RM XSP YEBX ERVO FA VEG WLWOICD GSCIO DUH DLINCE PQLQJ ZT PVV QULI APCLZVD RM QTORHSVLUAL HLG ZSWPDAIO EVA FZYJ WEDDSZ HF TVPPOFF SVF SDK XSTG KBV NKHRNP HK RVDWYSJ PJEZ WZULZPC PQH KSH OILCHO CW XHU ECP SWGZWB JSCCILHVO DUH ESS NWER RM TZHSN VRD D DMWW CB WKD RDR TE PAHILBLH TDWHRLC WV LTD RAOKS DUH DZAA HYTQNW ESOP GYZXSH YZH DOMP ELIY QCNUFEWLR HPFA ZFDW OMDECNM SPFHQP WSCSEO OLKPYR XSTLPL QJEV WBU QRY XHZ OJR R SDSJ ESCQGRYG FILCG PVV CLUK ALGOSU ZXA SQ LZH YEZZSIORS QBKTO DLPY QDOENH JEXP HDS ITQN IYDBWFVO D UIH MSWFVC WOI CTBC QRXH AS ESS YFVLWBVP RCHZLX ZOS EZCG WK OHLT TYHK HYP WBRYPZO IEOHY XSP AEGKJ PVYYEOEBJ LQK XSPFA WK NRUWFXSZ VZX WOI CTBC URGH AS RZZHID FQUEEFFWZ CZQN PTQS BCI QLCI SFBZFVO BLECD WP DFTVVRPO VEG DTQK EYO WJ HYP JSSZX CB UFWOBQD NORS ZE ZHMEPR ZOIVQLWD NFADK MDJO TYHK HYP IVVPDHO CW EKL AZCZZ FLXRY KCPK KT R DKHHZH WJ HYP HHWE HVEGGPUZ SQ L BWAVWHZW QPON OEO WOI CTBC CW ARDIC ASNQVTYLH TEG PWDP KHH YZK YCDP LA EMLBZCEPG NSWWII PLE WOIY DCISKSLUK SLDLSEPG ALLE HDS ITQN HTO BKH ZYWLRO TH SOJ ALJOPO IL PP EKL QZDH QBCTNLPJ NFAOKFUL MXLUEBRMOL E SZPXWK MLSFZ MOCUZYV VJ ESS OVZCH MSC EVA HZXH DMWW GKCE NRTI HSSJ VFMEPXD HWHZ JSDWI ESS BCIEXUID ZT WZC 
""".replace(" ", "").replace("-", "")

fourgramms = {}

print(ciphertext)

for i in range(len(ciphertext)-4):
    fourgramm = ciphertext[i:i+4]
    if fourgramms.get(fourgramm):
        fourgramms[fourgramm] += 1
    else:
        fourgramms.update({fourgramm: 1})

print([k for k,v in fourgramms.items() if v > 1])

_1 = []

for i in range(0, len(ciphertext)-10, 10):
    _1.append(ciphertext[i])

_1_cnt = Counter(_1)

_2 = []

for i in range(1, len(ciphertext)-10, 10):
    _2.append(ciphertext[i])

_2_cnt = Counter(_2)

_3 = []

for i in range(2, len(ciphertext)-2, 4):
    _3.append(ciphertext[i])

_3_cnt = Counter(_3)

_4 = []

for i in range(3, len(ciphertext)-1, 4):
    _4.append(ciphertext[i])


_4_cnt = Counter(_4)




import matplotlib.pyplot as plt

for i in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    if not _2_cnt.get(i):
        _2_cnt[i] = 0

data = dict(sorted(_2_cnt.items(), key=lambda x: x[0]))

x = [i for i in data.keys()]
y = [i/len(_2) for i in data.values()]

plt.bar(x, y, linestyle='-', color='b', label="Sample Line")

plt.xlabel("Буква")
plt.ylabel("Частота")
plt.legend()

plt.show()